flags:
extra-package-dbs: []
ghc-options:
  hscolour: -w
allow-newer: true # 8.10.1
packages:
extra-deps:
- tasty-rerun-1.1.14
- fgl-visualize-0.1.0.1
- located-base-0.1.1.1
- hashable-1.3.0.0
- optics-0.3
- optics-core-0.3
- optics-th-0.3
- optics-extra-0.3
- Diff-0.4.0
- aeson-1.4.7.1
- th-compat-0.1
resolver: lts-16.8
compiler: ghc-8.10.2